### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by FQMLOL** [liquidbounceplusreborn/LiquidbouncePlus-Reborn#18]
such as the title..if I run the client for more than 5mins it takes up 10000M mem

**Comment by FQMLOL** [comment]
MemFix mod not working

**Comment by FQMLOL** [comment]
![image](https://user-images.githubusercontent.com/108399321/213816776-3c4bfbb8-97a4-4809-91ca-58b3829216f4.png)

**Comment by randomguy3725** [comment]
Already fixed?? download beta

**Comment by FQMLOL** [comment]
OK fixed
