### ISSUE TITLE
Killaura "searchrange"

### ISSUE THREAD

**Issue by Diotek0** [liquidbounceplusreborn/LiquidbouncePlus-Reborn#55]
killaura only rotate to the target when the target is in attackrange. But it does not rotate when target is in searchrange. It is a bug or something?

**Comment by 4pii4** [comment]
fixed with https://github.com/liquidbounceplusreborn/LiquidbouncePlus-Reborn/commit/e5dfaf2222dc1af8847b8c508162f9fa5536158a
