### ISSUE TITLE
is this is a bugs?

### ISSUE THREAD

**Issue by Diotek0** [liquidbounceplusreborn/LiquidbouncePlus-Reborn#56]
![image](https://github.com/liquidbounceplusreborn/LiquidbouncePlus-Reborn/assets/136789915/9d253a3c-df12-4a5e-b5db-94cbfa2f8856)

**Comment by Diotek0** [comment]
it is not showing any server status or ping or everythings else. Please note: all server in my server list are online and i can join it

**Comment by 4pii4** [comment]
Hmm, I haven't encountered this problem before. Can u provide some more information, like are you using a VPN or give the console output?

**Comment by Diotek0** [comment]
Sorry that was my issue
