### ISSUE TITLE
shader or texture or render issue (i forgur) 

### ISSUE THREAD

**Issue by fuckusfm** [liquidbounceplusreborn/LiquidbouncePlus-Reborn#62]
https://github.com/liquidbounceplusreborn/LiquidbouncePlus-Reborn/assets/153373550/9d20fe5e-6d33-401b-88dd-b2ce05d458a1

the video explains everything
i was using latest commit in the vid

to recreate this:
use this [hud.json](https://github.com/liquidbounceplusreborn/LiquidbouncePlus-Reborn/files/13823398/hud.json) cfg
run .panic all if u have any modules on
turn on killaura walk (turn on rotations if you want your eyes to hurt)
and done

**Comment by LuckySynx** [comment]
randomguy best skidding moment 🔝

**Comment by randomguy3725** [comment]
Dead client,making new lb fork
